package ken.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-10-16T11:55:40.699+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://service.ken/", name = "ServiceDemo")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceDemo {

    @WebMethod
    @RequestWrapper(localName = "findAllUser", targetNamespace = "http://service.ken/", className = "ken.service.FindAllUser")
    @ResponseWrapper(localName = "findAllUserResponse", targetNamespace = "http://service.ken/", className = "ken.service.FindAllUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ken.service.User> findAllUser()
;
}
